name: release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup go
        uses: actions/setup-go@v1
        with:
          go-version: 1.17
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build
        run: make -j dist
      - name: Test
        run: go test -timeout=600s -v
      - name: Upload release assets
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/docker-mirror-linux-amd64
          tag: ${{ github.ref }}
